name: CI and CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # ==============
  # CI task
  # ==============
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/chinathaip/testargocd:${{ env.GITHUB_SHA }}
        
      - name: Integration test inside Docker-compose cleanup
        run: docker-compose -f docker-compose.test.yml down
    
      - name: Integration test inside Docker-compose
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from it_tests

      - name: Login ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/chinathaip/testargocd:${{ env.GITHUB_SHA }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}



  # ==============
  # CD task - access the repo that has kubernetes config files, and change the pods' container image
  # ==============
  gitops-versioning:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: chinathaip/deployargo
          persist-credentials: false
          fetch-depth: 0
      - name: change image tag
        run: |
          git --version
          git config user.name "chinathaip"
          git config user.email "cartoonabe@gmail.com"
          sed -i -E "s/ghcr.io\/chinathaip\/testargocd.*$/ghcr.io\/chinathaip\/testargocd:${GITHUB_SHA}/" k8s/deployment.yml
          git add k8s/deployment.yml
          git commit -m "🤖 change docker image version to ${GITHUB_SHA}"
      # line 87: 
      # open the kube-gitios/deployment.yml file in the 'devops-argocd' repo(tutorial), 
      # try to change the value of 'image' inside this file
      # by searching for regular expression: find any line that has a pattern of ghcr.io/aorjoa-training/devops-go-example
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          repository: chinathaip/deployargo
          branch: main